# Generated by Django 4.0.2 on 2022-03-24 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, default=0.0, max_digits=10, null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='user',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, default=0.0, max_digits=10, null=True, verbose_name='Долгота'),
        ),
    ]
